deploy:
  stage: deploy
  script:
    # Git konfiguratsiyasini sozlash
    - git config --global user.email "xayrullo936@gmail.com"
    - git config --global user.name "Xayrulla Ochildiyev"
    # Agar HEAD detached bo'lsa, yangi branch yaratish
    - git checkout -b temp-branch || echo "Branch allaqachon mavjud"
    - git branch -M main
    # GitHub repositoryni sozlash
    - git remote remove origin || echo "Remote origin mavjud emas"
    - git remote add origin https://${GITHUB_TOKEN}@github.com/XayrullaOdilivich/Printzaprafka.git
    # GitHub'ga push qilish
    - git push -u origin main || echo "Push muvaffaqiyatsiz bo'ldi"
