image: node:22

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    # Git konfiguratsiyasini o'rnatish
    - git config --global user.email "xayrullo936@gmail.com"
    - git config --global user.name "Xayrulla Ochildiyev"
    # GitHub repositoryga sozlash
    - echo "# Printzaprafka" >> README.md
    - git add .
    - git commit -m "first commit" || echo "Commit allaqachon mavjud"
    - git branch -M main || echo "Branch main allaqachon mavjud"
    - git remote remove origin || echo "Remote origin yo'q edi"
    - git remote add origin https://github.com/XayrullaOdilivich/Printzaprafka.git
    - git push -u origin main
