image: node:22

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

pages:
  stage: deploy
  script:
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
deploy:
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/XayrullaOdilivich/Printzaprafka.git
    - git push github $CI_COMMIT_REF_NAME
