stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - npm install
    - npm test

build_job:
  stage: build
  script:
    - npm run build

deploy_job:
  stage: deploy
  script:
    - echo "Deploying to production"
  only:
    - main
