deploy:
  stage: deploy
  script:
    # Git konfiguratsiyasini o'rnatish
    - git config --global user.email "xayrullo936@gmail.com"
    - git config --global user.name "Xayrulla Ochildiyev"
    # GitHub repositoryga sozlash
    - echo "# Printzaprafka" >> README.md
    - git add .
    - git commit -m "initial commit" || echo "Commit allaqachon mavjud"
    - git branch -M main
    - git remote remove origin || echo "Remote origin mavjud emas"
    - git remote add origin https://github.com/XayrullaOdilivich/Printzaprafka.git
    - git push -u origin main || echo "Push muvaffaqiyatsiz bo'ldi"
